artikel/urls.py
from django.urls import path 
from . import views

app_name = 'artikel'

urlpatterns = [
    path('', views.home, name="home"), 
    path('add/', views.add, name="add"), 
    path('details/<int:article_id>/', views.details, name="details"),
    path('delete/<int:article_id>/', views.delete, name="delete"),
    path('edit/<int:article_id>/', views.edit, name="edit"),
]

tk1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('lapordiri/', include('lapordiri.urls')),
    path('artikel/', include('artikel.urls')), 
    path('donasi/', include('Donasi.urls')),
    path('forum/', include('forum.urls'))
]

artikel/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=180)
    img = models.URLField(max_length=300)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    time_posted = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    

artikel/forms.py
from django import forms 
from .models import Article 
from django.forms import widgets, TextInput, Textarea, DateTimeInput

class ArticleForm(forms.ModelForm):
    class Meta :
        model = Article
        fields = ['title', 'img', 'content']
        widgets = {
            'title' : TextInput(attrs={'placeholder' : 'Nama', 'required' : True}), 
            'img' : TextInput(attrs={'placeholder' : 'URL gambar, misal : https://picsum.photos/450/300?image=1072', 'required' : True}), 
            'content' : Textarea(attrs={'placeholder' : 'Konten', 'required' : True}),
            'time_posted': DateTimeInput(format='%d/%m/%Y %H:%M')
        }

artikel/views.py
from django.shortcuts import render, redirect 
from .models import Article 
from .forms import ArticleForm
from django.contrib.auth.decorators import login_required

def home(request):
    article = Article.objects.all()
    return render(request,"artikel/home.html", {'article' : article})

def details(request, article_id):
    obj = Article.objects.get(id=article_id)
    return render(request, 'artikel/details.html', {'obj' : obj})

@login_required
def add(request):
    form = ArticleForm(request.POST)
    if (form.is_valid() and request.method == 'POST' ) :
        user = request.user 
        instance = form.save(commit=False)
        instance.author_id = user.id 
        instance.save()
        return redirect('artikel:home')
    return render(request, 'artikel/add.html', {'form' : form, } )

@login_required
def delete(request, article_id):
    obj = Article.objects.get(id=article_id)
    obj.delete()
    return redirect('artikel:home')

@login_required
def edit(request, article_id):
    obj = Article.objects.get(id=article_id)
    form = ArticleForm(instance=obj)
    if request.method == "POST" :
        form = ArticleForm(request.POST, instance=obj)
        if form.is_valid() : 
            user = request.user 
            instance = form.save(commit=False)
            instance.author_id = user.id 
            instance.save()
            return redirect('artikel:home')
    return render(request, 'artikel/edit.html', {'form': form,})
   
        

artikel/templates/artikel/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block meta %}
    <title>Tambah Artikel</title>
    <link rel="stylesheet" type="text/css" href="{% static 'artikel.css' %}">
{% endblock meta %}

{% block content %}
<div class="container pb-5">

  <div class="row1">
    <h1>Tambah Artikel</h1>
  </div>

 <div class="row4">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          {{ form|crispy }}
        </fieldset>
        <div class="row3">
          <button class="button-fill" type="submit"> Tambah </button>
        </div>
      </form>
  </div>

</div>

{% endblock content %}

artikel/templates/artikel/details.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>{{obj.title}}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'artikel.css' %}">
{% endblock meta %}

{% block content %}

<div class="container pb-5">

    <div class="row1 text-center">
        <h3>{{obj.title}}</h3>

        <p class="text-muted">{{obj.time_posted}}</p>
        <div class="row mx-auto" style="justify-content:center;">
       
         {% if obj.author.profile.isTenagaMedis %}
              <img src="{% static 'images/tenaga_medis.svg' %}" width="10%" alt="" style="margin-right:0.25rem;">
              <p style="margin-bottom:unset; color:#00BFA6">{{obj.author}}</p>
            {% else %}
              <img src="{% static 'images/default.svg' %}" width="10%" alt="" style="margin-right:0.25rem;">
              <p style="margin-bottom:unset;">{{obj.author}}</p>
            {% endif %}
        </div>
    </div>
       
    <div class="row2">
        <img src="{{obj.img}}" width="75%" height="40%" id="placeholder" alt="">
    </div>

    <div class="row3 text-justify">
        <p style="word-break:break-word;">{{obj.content | linebreaksbr}}</p>
    </div>

</div>

<script type='text/javascript'>
  document.getElementById('placeholder').onerror = function() { 
    document.getElementById('placeholder').src = "https://via.placeholder.com/300?text=No+image"; 
  }
</script>

{% endblock content %}

artikel/templates/artikel/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block meta %}
    <title>Edit Artikel</title>
    <link rel="stylesheet" type="text/css" href="{% static 'artikel.css' %}">
{% endblock meta %}

{% block content %}
<div class="container pb-5">

    <div class="row1">
        <h1>Edit Artikel</h1>
  </div>

    <div class="row4">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
            {{ form|crispy }}
            </fieldset>
            <div class="row3">
            <button class="button-fill" type="submit"> Simpan </button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

artikel/templates/artikel/home.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
<title>Artikel</title>
<link rel="stylesheet" type="text/css" href="{% static 'artikel.css' %}">
{% endblock meta %}

{% block content %}

<div class="container pb-5">

    <div class="row1">
        <h1>Artikel</h1>
        <a class="btn btn-primary" href="{% url 'artikel:add' %}" role="button">+ Tambah Artikel</a>
        <br>
    </div>
 
    {% if article %}

    {% for a in article reversed %}

  <!-- Card Start -->

  <div class="card">
    <div class="row ">

      <div class="col-md-4" style="display:flex; align-items:center;">
        <img class="d-flex w-100" src="{{a.img}}" width="100%" alt="" id="placeholder" style="overflow:hidden;">
      </div>

        <div class="col-md-8 px-3">
          <div class="card-block px-3">
          <br>

          <h2 class="card-title" style="font-weight:bold;">{{a.title}}</h2>
            <p class="text-muted">{{a.time_posted}}</p>

          <div class="row mx-auto my-3">
            {% if a.author.profile.isTenagaMedis %}
              <img src="{% static 'images/tenaga_medis.svg' %}" width="4%" alt="" style="margin-right:0.5rem;">
              <p style="margin-bottom:unset; color:#00BFA6">{{a.author}}</p>
            {% else %}
              <img src="{% static 'images/default.svg' %}" width="4%" alt="" style="margin-right:0.5rem;">
              <p style="margin-bottom:unset;">{{a.author}}</p>
            {% endif %}
          </div>

          <p class="card-text">
            {{a.content | truncatewords:50 }}
          </p>

          <a href="{% url 'artikel:details' article_id=a.id %}" class="text-decoration-none">Read More</a>
          <br>
          <br>
            {% if a.author_id == user.id %}

            <div class="text-right">
                <a class="text-decoration-none" href="{% url 'artikel:edit' article_id=a.id %}" style="margin-right:0.5rem;">Edit Artikel</a>
                <a class="text-decoration-none" href="{% url 'artikel:delete' article_id=a.id %}" style="color:red;"> Hapus Artikel</a>
            </div>

            {% endif %}

           <br>
           <br>
        </div>
      </div>
      
       
            </div>
        </div>


  <!-- End of card -->

    {% endfor %}

    {% else %}
    <div class="row2">
    <p>Belum ada artikel baru</p>
    </div>
    {% endif %}


</div>

<script type='text/javascript'>
  document.getElementById('placeholder').onerror = function() { 
    document.getElementById('placeholder').src = "https://via.placeholder.com/300?text=No+image"; 
  }
</script>


{% endblock content %}