main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/',views.register, name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='main/home.html'), name='logout')
]

tk1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('lapordiri/', include('lapordiri.urls')),
    path('artikel/', include('artikel.urls')), 
    path('donasi/', include('Donasi.urls')),
    path('forum/', include('forum.urls'))
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    isTenagaMedis = models.BooleanField()

    def __str__(self):
        return self.user.username

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    isTenagaMedis = forms.BooleanField(required=False, label="Saya tenaga medis")
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

main/views.py
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm
from .models import Profile

def home(request):
    return render(request, 'main/home.html')

def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            isTenagaMedis = form.cleaned_data.get('isTenagaMedis')
            Profile.objects.create(user=user, isTenagaMedis=isTenagaMedis)
            return redirect('main:login')
    else:
        form = UserRegistrationForm()
    return render(request, 'main/register.html', {'form':form})

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Seputar Covid</title>
<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
{% endblock meta %}

{% block content %}
<div class="container pb-5">

  <div class="row1">
    <h1>SeputarCOVID</h1>
    <h5> portal aplikasi seputar COVID-19</h5>
  </div>
  
  <div class="row2">
    <img src="{% static 'img/welcome-image.svg' %}">
  </div>
  
  <div class="row3">
    {% if user.is_authenticated %}
        <h2> Selamat datang {{ user.username }}</h2>
    {% else %}
        <a class="button-fill" href="{% url 'main:register' %}"> Daftar </a>
        <a class="button-outline" href="{% url 'main:login' %}"> Login </a>
    {% endif %}
  </div>
</div>
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block meta %}
<title>Seputar Covid</title>
<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
{% endblock meta %}

{% block content %}
<div class="container pb-5">
  <div class="row1">
    <h1>Login</h1>
  </div>
  
  <div class="row1">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          {{ form|crispy }}
        </fieldset>
        <div class="row3">
          <button class="button-fill" type="submit"> Login </button>
        </div>
      </form>
      <small class="text-muted">
        Belum punya akun? <a class="ml-2" href="{% url 'main:register' %}">Daftar</a>
      </small>
  </div>
</div>
  
{% endblock content %}

main/templates/main/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block meta %}
<title>Seputar Covid</title>
<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
{% endblock meta %}

{% block content %}
<div class="container pb-5">
  <div class="row1">
    <h1>Buat akun baru</h1>
  </div>
  
  <div class="row1">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          {{ form|crispy }}
        </fieldset>
        <div class="row3">
          <button class="button-fill" type="submit"> Daftar </button>
        </div>
      </form>
      <small class="text-muted">
        Sudah punya akun? <a class="ml-2" href="{% url 'main:login' %}">Login</a>
      </small>
  </div>

</div>
  
   
      
  
{% endblock content %}